experiment:
  name: "I3DBaselineInception"
  model_save_path: "./model" # path to save the trained model
  experiment_number: 1 # do not forget to change the experiment number
  log_path: "./log" # Path to save the log file

data:
  name: "Mecanno"
  util_location: "framework_activity_recognition.datautils.prepare_meccano" # Location of the data utility script
  sampler:
    use: True
  
  frame_size: 224
  num_frames: 32     # Similar to the authors of the mecanno dataset  
  sampling_rate: 2    # Similar to the authors of the mecanno dataset
  train_jitter_scales: [256, 320]
  train_crop_size: 224
  test_crop_size: 256
  input_channel_num: [3]

student:
  location: "architecture.i3d_inception.I3DLogit"
  modality: "rgb"
  dropout_prob: 0.5
  name: "inception"

pretraining:
  use: True
  model_num_classes: 400
  fine_tune_only_last_layer: False
  last_layer_variable: "conv3d_0c_1x1"
  last_layer_class: "architecture.i3d_inception.Unit3Dpy"
  last_layer_parameter: {"in_channels": 1024, "kernel_size": !!python/tuple [1, 1 ,1], "activation": null, "use_bias": True, "use_bn": False}

train:
  modality: "train_baseline"
  epoch: 200
  criterion: 
    name : "CrossEntropyLoss"
  optimizer:
    name: "SGD"
    parameter: {"lr": 0.1, "momentum": 0.9, weight_decay: 0.0001}
  batch_size: 12
  num_workers: 4

  scheduler:
    use: True # Whether to use a learning rate scheduler
    name: "CosineAnnealingLR" # Scheduler type
    #parameter: {"milestones": [50,100,200,300,400,500,600,700], "gamma": 0.2} # Scheduler parameters
    parameter: {"T_max": 80, "eta_min": 0.0001} # Scheduler parameters
  
  test_rate: 5 # Frequency of testing (e.g., every 5 epochs)
  pin_memory: true # Whether to use pinned memory for data loading
