experiment:
  name: "I3DBaseline"
  model_save_path: "./model" # path to save the trained model
  experiment_number: 0 # do not forget to change the experiment number

data:
  name: "Mecanno"
  util_location: "framework_activity_recognition.datautils.prepare_meccano" # Location of the data utility script
  data_path: # path to folder containing downsampled Drive&Act video data
  sampler:
    use: True
  n_frame: 16 # 32 64
  frame_size: 224

student:
  location: "architecture.i3d_inception.I3DLogit"
  modality: "rgb"
  dropout_prob: 0.5
  name: "inception"

pretraining:
  use: True
  path: # path to I3D model pretrained with Kinetics-400
  model_num_classes: 400
  fine_tune_only_last_layer: False
  last_layer_variable: "conv3d_0c_1x1"
  last_layer_class: "architecture.i3d.Unit3Dpy"
  last_layer_parameter: {"in_channels": 1024, "kernel_size": !!python/tuple [1, 1 ,1], "activation": null, "use_bias": True, "use_bn": False}

train:
  modality: "train_baseline"
  epoch: 200
  criterion: 
    name : "CrossEntropyLoss"
  optimizer:
    name: "SGD"
    parameter: {"lr": 0.1, "momentum": 0.9}
  batch_size: 15
  num_workers: 4

  scheduler:
    use: True # Whether to use a learning rate scheduler
    name: "ReduceLROnPlateau" # Scheduler type
    #parameter: {"milestones": [50,100,200,300,400,500,600,700], "gamma": 0.2} # Scheduler parameters
    parameter: {"factor": 0.1, "patience": 10, "threshold": 0.0001, "min_lr": 0.0001} # Scheduler parameters
  
  test_rate: 5 # Frequency of testing (e.g., every 5 epochs)
  pin_memory: False # Whether to use pinned memory for data loading

config:
  path: ""