#### Configs slowFast framework ####
model:
  name: "SlowFast"  # Default model architecture
  num_classes: 400
  dropout_rate: 0.5
  loss_func: "cross_entropy"
  head_act: "softmax"
  act_checkpoint: false
  detach_final_fc: false
  frozen_bn: false
  fp16_allreduce: false

contrastive:
  temperature: 0.07
  dim: 128
  queue_len: 65536
  momentum: 0.5
  momentum_annealing: false
  type: "mem"
  interp_memory: false
  mem_type: "1d"
  num_classes_downstream: 400
  num_mlp_layers: 1
  mlp_dim: 2048
  bn_mlp: false
  bn_sync_mlp: false
  local_shuffle_bn: true
  sequential: false
  simclr_dist_on: true
  swav_queue_len: 0
  knn_on: true

solver:
  base_lr: 0.1
  lr_policy: "cosine"
  cosine_end_lr: 0.0
  momentum: 0.9
  dampening: 0.0
  nesterov: true
  weight_decay: 0.0001
  warmup_factor: 0.1
  warmup_epochs: 0.0
  warmup_start_lr: 0.01
  optimizing_method: "sgd"
  max_epoch: 300
  layer_decay: 1.0

bn:
  use_precise_stats: false
  num_batches_precise: 200
  weight_decay: 0.0
  norm_type: "batchnorm"
  num_splits: 1
  num_sync_devices: 1
  global_sync: false

augmentation:
  enable: false
  num_sample: 1
  color_jitter: 0.4
  aa_type: "rand-m9-mstd0.5-inc1"
  interpolation: "bicubic"
  re_prob: 0.25
  re_mode: "pixel"
  re_count: 1
  re_split: false
  mask_window_size: [8, 7, 7]
  mask_ratio: 0.0

tensorboard:
  enable: false
  log_dir: ""
  confusion_matrix:
    enable: false
    figsize: [8, 8]
  histogram:
    enable: false
    topk: 10
    figsize: [8, 8]
  model_vis:
    enable: false
    model_weights: false
    activations: false
    input_video: false
    grad_cam:
      enable: true
      use_true_label: false
      colormap: "viridis"

misc:
  num_gpus: 1
  num_shards: 1
  shard_id: 0
  output_dir: "."
  rng_seed: 1
  log_period: 10

############################################# Confgis for our framework #############################################

experiment:
  name: "I3DBaselineResnet" # Name of the experiment
  model_save_path: "./model" # path to save the trained model
  experiment_number: 0 # do not forget to change the experiment number
  log_path: "./log" # Path to save the log file


student: # Student model configuration
  location: "architecture.i3d_slowfast.ResNet" # Location of the student model script
  name: "resnet" # Name of the student model


### Common configurations between frameworks ###
data:
  path_to_data_dir: ""
  path_label_separator: " "
  path_prefix: ""
  mean: [0.45, 0.45, 0.45]
  std: [0.225, 0.225, 0.225]
  input_channel_num: [3, 3]
  train_crop_size: 224
  test_crop_size: 256
  target_fps: 30
  train_jitter_fps: 0.0
  decoding_backend: "torchvision"
  decoding_short_size: 256
  random_flip: true
  multi_label: false
  ensemble_method: "sum"
  reverse_input_channel: false
  name: "Mecanno"
  util_location: "framework_activity_recognition.datautils.prepare_meccano" # Location of the data utility script
  sampler:
    use: True
  
  frame_size: 224
  num_frames: 8     # Similar to the authors of the mecanno dataset  
  sampling_rate: 8    # Similar to the authors of the mecanno dataset
  train_jitter_scales: [256, 320]
  input_channel_num: [3, 3]

train: # Training configuration
  modality: "train_baseline" # Training modality
  epoch: 200 # Number of training epochs
  criterion: 
    name : "CrossEntropyLoss" # Loss function
  optimizer:
    name: "AdamW" # Optimizer type
    parameter: {"lr": 0.1, "weight_decay": 0.0001}
  batch_size: 96 # Batch size for training
  num_workers: 8 # Number of worker threads for data loading
  scheduler:
    use: True # Whether to use a learning rate scheduler
    name: "CosineAnnealingLR" # Scheduler type
    #parameter: {"milestones": [50,100,200,300,400,500,600,700], "gamma": 0.2} # Scheduler parameters
    parameter: {"T_max": 40, "eta_min": 0.0001} # Scheduler parameters
  test_rate: 10 # Frequency of testing (e.g., every 5 epochs)
  pin_memory: False # Whether to use pinned memory for data loading
