experiment: # Experiment configuration
  name: "MobileNetBaseline" # Name of the experiment
  model_save_path: "./results" # Path to save the trained model
  experiment_number: 1 # Experiment number, should be changed for each new experiment
  log_path: "./log" # Path to save the log file

data: # Data configuration
  name: "Meccano" # Name of the dataset
  util_location: "framework_activity_recognition.datautils.prepare_meccano" # Location of the data utility script
  sampler:
    use: true # Whether to use a Imbalanced data sampler 

  num_frames: 32     # Similar to the authors of the mecanno dataset  
  sampling_rate: 2    # Similar to the authors of the mecanno dataset
  train_jitter_scales: [256, 320]
  train_crop_size: 224
  test_crop_size: 256
  input_channel_num: [3]

student: # Student model configuration
  location: "architecture.mobilenet.MobileNetLogit" # Location of the student model script
  width_mult: 1 # Width multiplier for the MobileNet model, 0.5 is the smallest (possible values are 0.5, 1.0, 1.5, 2.0)
  dropout_prob: 0.2 # Dropout probability
  name: "inception" # Name of the student model

pretraining: # Pretraining configuration
  use: True # Whether to use a pretrained model (in tanma paper, they used a pretrained model on kinetics-600)
  path: "" # Path to the pretrained model
  model_num_classes: 600 # Number of classes in the pretrained model
  fine_tune_only_last_layer: False # Whether to fine-tune only the last layer

train: # Training configuration
  modality: "train_baseline" # Training modality
  epoch: 100 # Number of training epochs
  criterion: 
    name : "CrossEntropyLoss" # Loss function
  optimizer:
    name: "SGD" # Optimizer type
    parameter: {"lr": 0.1, "momentum": 0.9, "weight_decay": 0.00001} # Optimizer parameters
  batch_size: 96 # Batch size for training
  num_workers: 8 # Number of worker threads for data loading
  scheduler:
    use: True # Whether to use a learning rate scheduler
    name: "ReduceLROnPlateau" # Scheduler type
    #parameter: {"milestones": [50,100,200,300,400,500,600,700], "gamma": 0.2} # Scheduler parameters
    parameter: {"factor": 0.1, "patience": 10, "threshold": 0.0001, "min_lr": 0.0001} # Scheduler parameters
  test_rate: 10 # Frequency of testing (e.g., every 5 epochs)
  pin_memory: False # Whether to use pinned memory for data loading